In [3]:
import pickle

In [4]:
X = pickle.load(open('X.pkl', 'rb'))
y = pickle.load(open('y.pkl', 'rb'))

In [5]:
X

array([[[[  1,  11,  35],
         [  1,  12,  34],
         [  0,  10,  30],
         ...,
         [ 77,  69,  56],
         [ 76,  68,  55],
         [ 75,  67,  54]],

        [[  1,  11,  35],
         [  1,  12,  34],
         [  1,  12,  32],
         ...,
         [ 77,  69,  56],
         [ 76,  68,  55],
         [ 75,  67,  54]],

        [[  2,  12,  36],
         [  2,  13,  35],
         [  1,  12,  32],
         ...,
         [ 77,  69,  56],
         [ 77,  69,  56],
         [ 77,  69,  56]],

        ...,

        [[  1,   7,  42],
         [  1,   7,  42],
         [  2,   8,  43],
         ...,
         [  2,  21,  54],
         [ 12,  29,  62],
         [  0,  15,  48]],

        [[ 10,  16,  51],
         [  5,  11,  46],
         [  5,  11,  46],
         ...,
         [  4,  22,  51],
         [  6,  22,  51],
         [  4,  20,  49]],

        [[  0,  13,  49],
         [  4,  10,  45],
         [  1,   4,  35],
         ...,
         [  2,  19,  52],
        

In [6]:
y

array([0, 1, 1, ..., 1, 1, 1])

In [7]:
X = X/255

In [8]:
X

array([[[[0.00392157, 0.04313725, 0.1372549 ],
         [0.00392157, 0.04705882, 0.13333333],
         [0.        , 0.03921569, 0.11764706],
         ...,
         [0.30196078, 0.27058824, 0.21960784],
         [0.29803922, 0.26666667, 0.21568627],
         [0.29411765, 0.2627451 , 0.21176471]],

        [[0.00392157, 0.04313725, 0.1372549 ],
         [0.00392157, 0.04705882, 0.13333333],
         [0.00392157, 0.04705882, 0.1254902 ],
         ...,
         [0.30196078, 0.27058824, 0.21960784],
         [0.29803922, 0.26666667, 0.21568627],
         [0.29411765, 0.2627451 , 0.21176471]],

        [[0.00784314, 0.04705882, 0.14117647],
         [0.00784314, 0.05098039, 0.1372549 ],
         [0.00392157, 0.04705882, 0.1254902 ],
         ...,
         [0.30196078, 0.27058824, 0.21960784],
         [0.30196078, 0.27058824, 0.21960784],
         [0.30196078, 0.27058824, 0.21960784]],

        ...,

        [[0.00392157, 0.02745098, 0.16470588],
         [0.00392157, 0.02745098, 0.16470588]

In [9]:
X.shape


(23000, 100, 100, 3)

In [ ]:
X = X.reshape(-1, 60, 60, 1)

In [ ]:
!pip install keras Sequential activations tensorflow

In [10]:
from keras.models import Sequential
from keras.layers import Conv2D, MaxPooling2D, Dense, Flatten

2024-04-30 15:25:46.495563: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


In [11]:
model = Sequential()

model.add(Conv2D(64, (3,3), activation = 'relu'))
model.add(MaxPooling2D((2,2)))

model.add(Conv2D(64, (3,3), activation = 'relu'))
model.add(MaxPooling2D((2,2)))

model.add(Flatten())

model.add(Dense(128, input_shape = X.shape[1:], activation = 'relu'))

model.add(Dense(2, activation = 'softmax'))

/home/jkozik/projects/Cats-Vs-Dogs-Prediction/venv/lib/python3.10/site-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [12]:
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [13]:
model.fit(X, y, epochs=5, validation_split=0.1)

Epoch 1/5


2024-04-30 15:26:26.628484: W external/local_tsl/tsl/framework/cpu_allocator_impl.cc:83] Allocation of 2484000000 exceeds 10% of free system memory.


647/647 ━━━━━━━━━━━━━━━━━━━━ 542s 833ms/step - accuracy: 0.6012 - loss: 0.6766 - val_accuracy: 0.6583 - val_loss: 0.6577
Epoch 2/5
647/647 ━━━━━━━━━━━━━━━━━━━━ 556s 824ms/step - accuracy: 0.7217 - loss: 0.5523 - val_accuracy: 0.7526 - val_loss: 0.5028
Epoch 3/5
647/647 ━━━━━━━━━━━━━━━━━━━━ 555s 813ms/step - accuracy: 0.7993 - loss: 0.4289 - val_accuracy: 0.7778 - val_loss: 0.4724
Epoch 4/5
647/647 ━━━━━━━━━━━━━━━━━━━━ 561s 812ms/step - accuracy: 0.8525 - loss: 0.3300 - val_accuracy: 0.7757 - val_loss: 0.5085
Epoch 5/5
647/647 ━━━━━━━━━━━━━━━━━━━━ 559s 807ms/step - accuracy: 0.9286 - loss: 0.1829 - val_accuracy: 0.7657 - val_loss: 0.6538


In [ ]:
X.shape

In [ ]:
import time

time.time()

In [ ]:
type(1581428129.5990093)